### ISSUE TITLE
Task-1 A warm up task

### ISSUE THREAD

**Issue by insanecoder02** [opencodeiiita/Text-It#1]
Add your Name and Github_username in [contibutors.xml](https://github.com/opencodeiiita/Text-It/blob/master/app/src/main/res/values/contributors.xml) located in res/values folder.

**PS: This issue is open for all, so no need to claim this issue. You can directly create a pull request**

_Happy Contributing!😊_

**Comment by Apoorv012** [comment]
#5

**Comment by AnshikaSwirl** [comment]
done

**Comment by raj-kariya** [comment]
Updated the contributer.xml #49

**Comment by muffinboy19** [comment]
This issue is now over
