### ISSUE TITLE
Advancement in Technology

### ISSUE THREAD

**Issue by insanecoder02** [opencodeiiita/Text-It#101]
You have to change the logic of registeruser and LoginUser using **Firebase** in the project

you have to add the Firebase dependencies in your gradle file to use this

If you are a beginner, don't worry have a look in resources Server on Discord on how to integrate firebase🔥in your project!!!

**Comment by harshsingh554** [comment]
claim

**Comment by kushal7201** [comment]
Claim

**Comment by Rohit-110** [comment]
claim

**Comment by muffinboy19** [comment]
@Rohit-110

**Comment by muffinboy19** [comment]
reminder @Rohit-110 the task deadline is near
