### ISSUE TITLE
Show us your face

### ISSUE THREAD

**Issue by insanecoder02** [opencodeiiita/Text-It#102]
Add an ImageView in ResisterUser() in which user can upload its _profile image📷_ .

Also write the code in the kt file to implement this logic.

**NOTE:- your PR will only be merge if you have implemented it correctly.**

**Happy Contributing!!!!😉**

**Comment by Jarviss77** [comment]
claim

**Comment by insanecoder02** [comment]
assigned to @Jarviss77

**Comment by kushal7201** [comment]
Claim

**Comment by muffinboy19** [comment]
@Jarviss77  your deadline for the task  is near

**Comment by Jarviss77** [comment]
Will make a pr by EOD
If I get stuck I'll inform you

**Comment by muffinboy19** [comment]
done
