### ISSUE TITLE
Store the data

### ISSUE THREAD

**Issue by insanecoder02** [opencodeiiita/Text-It#103]
Create DataClass in which you can store user's 
- name
- email
- password
- image

**Note: Image is stored in string datatype**

**Comment by harshsingh554** [comment]
claim

**Comment by kushal7201** [comment]
c

**Comment by muffinboy19** [comment]
@harshsingh554  this issue is assigned to you

**Comment by muffinboy19** [comment]
sorry assigned to @kushal7201

**Comment by kushal7201** [comment]
I have unassigned me as my PR is merged
