### ISSUE TITLE
Register/Login using Firebase

### ISSUE THREAD

**Issue by insanecoder02** [opencodeiiita/Text-It#109]
Write the logic for login/registering the user using their email and password.

The authentication system has already been set for email/password (email may/may not be a valid email)

You can refer to the Firebase documentation for this task 
[Email Auth](https://firebase.google.com/docs/auth/android/email-link-auth)

**_PS_:- Firebase has integrated into the project, so there is no need to do it again**

**_Note_:- Also those who want to take this task have to share their email ID so that i can add you on the project and you can access with this [link](https://console.firebase.google.com/u/0/project/text-it-14055/overview).**

**Comment by insanecoder02** [comment]
assigned to @aashray374

**Comment by Aastha-ojha-20** [comment]
claim

**Comment by muffinboy19** [comment]
this issue for now is suspended
