### ISSUE TITLE
Dark/Light mode

### ISSUE THREAD

**Issue by insanecoder02** [opencodeiiita/Text-It#110]
Your task is to set the app theme for **light theme** (_by default_) i.e. system settings should not affect the app's theme.
you have to make the changes such that it should be constant in both the themes

**As of now**
- Light mode
 
![WhatsApp Image 2023-12-20 at 10 24 18_a15e0ab0](https://github.com/opencodeiiita/Text-It/assets/120731858/1fade10e-de69-47d5-ae83-4b28aeb3e974)

- dark mode

![WhatsApp Image 2023-12-20 at 10 24 19_705fc905](https://github.com/opencodeiiita/Text-It/assets/120731858/64f749b2-c789-4e21-90b6-fa2daec6eda1)

**Comment by kushal7201** [comment]
Claim

**Comment by kushal7201** [comment]
Claim

**Comment by k7aditya** [comment]
claim

**Comment by insanecoder02** [comment]
assigned to @kushal7201
