### ISSUE TITLE
Permisson Access

### ISSUE THREAD

**Issue by insanecoder02** [opencodeiiita/Text-It#111]
Ask the user for the following permissions before entering the app :-
- camera
- media

the permission should only be asked when the user is first using the app.

Note:- the permission dialog box should not open in settings it should be open in app itself.
like this :- 
![image](https://github.com/opencodeiiita/Text-It/assets/120731858/bd8c487b-ea2f-4f3f-986b-935a3dd5f9f2)

**also write the code if user deny (any permission) then the app should automatically closes.**

**Comment by criticic** [comment]
claim

**Comment by insanecoder02** [comment]
assigned to @criticic
