### ISSUE TITLE
Re-Design the Splash Screen

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/Text-It#115]
### Task Description
You have to change the design of the splash screen according to the given design. 🖌️

### Guideline

If you want to access the individual elements present in the design, you might need the Figma file. You can find  the figma link in the read me file

**Happy Contributing!** 🌟
---
![this](https://github.com/opencodeiiita/Text-It/assets/87519281/1cbdf115-cf30-436a-8133-811dce8113d2)

**Comment by Aastha-ojha-20** [comment]
claim

**Comment by insanecoder02** [comment]
assigned to @Aastha-ojha-20

**Comment by insanecoder02** [comment]
@Aastha-ojha-20 submit your PR before 10:00 pm otherwise it will be assigned to others

**Comment by DikshantK2004** [comment]
Claim
