### ISSUE TITLE
Re-design the Login Page

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/Text-It#116]
### Task Description
You are tasked with redesigning the login page. 🎨 The Figma link containing design details can be found in the README file. ⏳

### Guideline

To access the individual elements present in the design, refer to the Figma file mentioned in the README. 📎

**Deadline for Task: 2 days** ⌛

**Happy Redesigning!** 🌟
---
![thiiss](https://github.com/opencodeiiita/Text-It/assets/87519281/8ec27380-ee93-40a1-bd33-06dbc0f4e81d)

**Comment by Jarviss77** [comment]
claim

**Comment by criticic** [comment]
claim

**Comment by DikshantK2004** [comment]
Claim

**Comment by Jarviss77** [comment]
Will make a pr by night

**Comment by muffinboy19** [comment]
do it fast .. , or you can take a hint as someone  has already made the register page which is very simpler to it ,, you can just copy it and make some chnages in it
