### ISSUE TITLE
Redesign the SignUp Page

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/Text-It#117]
### Task Description
You are tasked with redesigning the Sign Up  page. 🎨 The Figma link containing design details can be found in the README file. ⏳

### Guideline

To access the individual elements present in the design, refer to the Figma file mentioned in the README. 📎

**Deadline for Task: 2 days** ⌛

**Happy Redesigning!** 🌟

---
![this](https://github.com/opencodeiiita/Text-It/assets/87519281/8ded3e0a-c520-4609-99c6-718980cf7b00)

**Comment by keshavkhetan123** [comment]
claim

**Comment by Aastha-ojha-20** [comment]
claim

**Comment by criticic** [comment]
claim

**Comment by keshavkhetan123** [comment]
claim

**Comment by muffinboy19** [comment]
Assigned to @criticic
