### ISSUE TITLE
Add a BottomNav Bar 

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/Text-It#118]
### Task Description
Your task is to add a bottom navigation bar to the login page, similar to the one mentioned in the design below. 🎨 The fragments for the navigation bar are already created, so no need to create them from scratch.

### Guideline

To access the individual elements present in the design, refer to the Figma link mentioned in the README file. ⏳

**Deadline for Task: 2 days** ⌛

**Happy Implementing!** 🌟
---
![thiss](https://github.com/opencodeiiita/Text-It/assets/87519281/14f67c74-ca81-422b-b131-5abd6a711af1)

**Comment by keshavkhetan123** [comment]
claim

**Comment by muffinboy19** [comment]
Assigned to [tonyStark-Jr](https://github.com/tonyStark-Jr)

**Comment by Aastha-ojha-20** [comment]
claim

**Comment by kushal7201** [comment]
Claim

**Comment by insanecoder02** [comment]
assigned to @kushal7201

**Comment by muffinboy19** [comment]
reminder @kushal7201

**Comment by kushal7201** [comment]
Ok

**Comment by insanecoder02** [comment]
@kushal7201 please submit before 3:30 pm otherwise the issue will be closed.

**Comment by kushal7201** [comment]
Claim

**Comment by kushal7201** [comment]
@insanecoder02  I'm working on the issue

**Comment by Rohit-110** [comment]
@insanecoder02 claim

**Comment by insanecoder02** [comment]
assigned to @Rohit-110

**Comment by muffinboy19** [comment]
@Rohit-110 can hurry
