### ISSUE TITLE
Desgin A XML

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/Text-It#119]
### Task Description
Your task is to create an XML layout for the bottom navigation bar, following the design provided below. 🎨 The fragments for the navigation bar are already created, so your focus is on crafting the XML layout.

### Guideline

To access the individual elements present in the design, refer to the Figma link mentioned in the README file. ⏳

**Deadline for Task: 2 days** ⌛

**Happy Coding!** 🌟
---
![it](https://github.com/opencodeiiita/Text-It/assets/87519281/e5a1e958-c5f9-479e-9c30-172fca210070)

**Comment by Aastha-ojha-20** [comment]
claim

**Comment by keshavkhetan123** [comment]
claim

**Comment by criticic** [comment]
claim

**Comment by k7aditya** [comment]
claim

**Comment by tonyStark-Jr** [comment]
claim
