### ISSUE TITLE
Create The HomeScreen 

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/Text-It#132]
### Create Accurate Home Screen Layout

🚀 **Task Overview:**
Create an accurate home screen layout within the next 2 days. This layout should include sections for displaying status and chat. For now, focus on adding RecyclerView placeholders for both sections.

#### Requirements:

1. **Status Section:**
   - The area where the status would be shown needs to be implemented.
   - ✨ Add a `RecyclerView` to dynamically display status updates.
   - 📊 Do not design the status layout, only add the `RecyclerView` for now.

2. **Chat Section:**
   - Implement the chat section on the home screen.
   - 🔄 Add a `RecyclerView` to handle the list of chat messages.
   - 🚫 Do not design the chat layout; your task is to insert the `RecyclerView` without writing the adapter code.

#### Deadline: 2 Days

📝 **Note:**
Do not write the adapter code for the RecyclerViews at this stage. This design if for the message fragment in the bottom nav bar 

Happy contributing! 🌟
---

![Home](https://github.com/opencodeiiita/Text-It/assets/87519281/6f02acf0-ab66-4fad-b599-3b45b7c20fbe)

**Comment by Rohit-110** [comment]
@muffinboy19  claim

**Comment by Mannxxx** [comment]
Claim

**Comment by muffinboy19** [comment]
@Rohit-110  send your email id

**Comment by MonuGit9** [comment]
claim
