### ISSUE TITLE
Write Adapter Code for Status Section RecyclerView

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/Text-It#133]
### Write Adapter Code for Status Section RecyclerView

🚀 **Task Overview:**
Your task is to write the adapter code for the RecyclerView in the status section. Additionally, create a Firestore collection named "status" and add sample documents with properties like username, status photo, and status upload time.

#### Requirements:

1. **Firestore Integration:**
   - 📂 Create a collection in Firestore named "status."
   - 📝 Create sample documents in the "status" collection with properties:
     - `username`
     - `statusPhoto`
     - `statusUploadTime`

2. **Adapter Code:**
   - ✍️ Write the adapter code for the RecyclerView in the status section.
   - 📥 Fetch data from the Firestore "status" collection.
   - 🚫 Do not add the RecyclerView to the XML layout at this stage; assume it will be added later.

📝 **Note:**
While working on this task, consider that the RecyclerView might not have been created yet. Write the adapter and fetching code, and assume the RecyclerView will be added to the XML layout later. Merge conflicts will be resolved when merging.

#### Dummy Data:
Create dummy data in Firestore with sample documents for testing.

  "username": "SampleUser",
  "statusPhoto": "url_to_sample_photo",
  "statusUploadTime": "sample_timestamp"
--- 
desgin for the status layout that would be used in recylerview
---
![fallal](https://github.com/opencodeiiita/Text-It/assets/87519281/a3d9b14a-d725-42da-8479-5dc15d499331)

**Comment by criticic** [comment]
claim

**Comment by muffinboy19** [comment]
@criticic  send your email id now the console is up

**Comment by muffinboy19** [comment]
done
