### ISSUE TITLE
Code for Contact Fragment

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/Text-It#134]
### Code for Contact Fragment

🚀 **Task Overview:**
Write the code for the Contact Fragment. If the Contact Fragment is not present, create it and add it to the Bottom Navigation Bar. The Contact Fragment should display a list of all users using a RecyclerView. Fetch the user data from Firebase.

#### Requirements:

1. **Firestore Integration:**
   - 📂 Create a collection in Firestore named "users."
   - 📝 Create sample documents in the "users" collection with properties:
     - `emailId`
     - `photo`
     - `name`

2. **Fragment Code:**
   - ✍️ Write the code for the Contact Fragment.
   - 📥 Fetch user data from the Firestore "users" collection.
   - 🔄 Add a `RecyclerView` to dynamically display the list of users.
   - ✍️ Write the adapter code for the user list in the Contact Fragment.

#### Dummy Data:
Create dummy data in Firestore with sample documents for testing.

{
  "emailId": "user1@example.com",
  "photo": "url_to_user1_photo",
  "name": "User 1"
}

---
![Contacts](https://github.com/opencodeiiita/Text-It/assets/87519281/10d8bdde-78c5-4961-98aa-2d8df34479da)

**Comment by CodinJack** [comment]
claim

**Comment by criticic** [comment]
claim

**Comment by insanecoder02** [comment]
assigned to @CodinJack

**Comment by CodinJack** [comment]
kindly assign it to someone else

**Comment by DikshantK2004** [comment]
claim

**Comment by Mannxxx** [comment]
Claim

**Comment by muffinboy19** [comment]
send your email id @DikshantK2004

**Comment by MonuGit9** [comment]
claim

**Comment by insanecoder02** [comment]
@DikshantK2004 your deadline is over. if u will not submit the PR by 9:00 pm today then it will be assigned to someone else

**Comment by DikshantK2004** [comment]
Hi please make it 10 pm atleast. I asked on discord for midnight. I have written most of the code just that I am not at home.

**Comment by DikshantK2004** [comment]
Hi please make it 11 pm atleast. I asked on discord for midnight. I have written most of the code just that I am not at home.

**Comment by muffinboy19** [comment]
Ok ok clam down
