### ISSUE TITLE
Create XML Layout for Settings Fragment

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/Text-It#135]
### Create XML Layout for Settings Fragment

🚀 **Task Overview:**
Create the XML layout for the Settings Fragment. If the Settings Fragment is not present, create it and integrate it into the appropriate section of the application.

#### Requirements:

1. **XML Layout:**
   - ✍️ Write the XML layout code for the Settings Fragment.
   - 🚫 Assume that the fragment is not yet created; create it from scratch.

#### Dummy Data:
No dummy data is required for this task; focus on the XML layout creation.

📝 **Note:**
Ensure that the Settings Fragment is created and integrated into the application. Merge conflicts will be resolved when merging.

Happy coding! 🌟
---
![Settings](https://github.com/opencodeiiita/Text-It/assets/87519281/307158dc-96e3-4bbc-a315-6e4808aba71a)

**Comment by Jarviss77** [comment]
claim

**Comment by osamabenlade** [comment]
claim

**Comment by Mannxxx** [comment]
Claim

**Comment by tushant-akar** [comment]
Please assign this to me
