### ISSUE TITLE
 Design User Profile Fragment

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/Text-It#136]
### Design User Profile Fragment

🚀 **Task Overview:**
Design the User Profile Fragment by creating a new fragment dedicated to displaying user profile information.

#### Requirements:

1. **Fragment Design:**
   - ✍️ Create a new fragment for the User Profile.
   - 🎨 Design the layout to display user profile information such as username, profile photo, and other relevant details.

#### Dummy Data:
No dummy data is required for this task; focus on designing the User Profile Fragment.

📝 **Note:**
Ensure that the User Profile Fragment is created and integrated into the application. Merge conflicts will be resolved when merging.

Happy designing! 🌟

---
![Uploading User profile.jpg…]()

**Comment by Rohit-110** [comment]
Claim

**Comment by criticic** [comment]
claim

**Comment by insanecoder02** [comment]
assigned to @criticic
