### ISSUE TITLE
Repair Google Authentication in Login/SignUp Page

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/Text-It#137]
### Repair Google Authentication in Login/SignUp Page

🚀 **Task Overview:**
Fix the Google authentication code on the Login/SignUp page. Ensure users can successfully sign in or sign up using their Google accounts. After authentication, add a new user using their Google account details and redirect them to the HomeActivity.

#### Requirements:

1. **Google Authentication:**
   - 🛠️ Repair the Google authentication code in the Login/SignUp page.
   - 📲 Ensure users can log in or sign up using their Google accounts.

2. **User Creation:**
   - 🧑‍💻 Add a new user using the Google account details.

3. **Redirection:**
   - 🔄 After successful authentication, redirect the user to the HomeActivity.

📝 **Note:**
Verify that the Google authentication works seamlessly from the Login/SignUp page, and users are properly redirected to the HomeActivity. Merge conflicts will be resolved when merging.

Happy coding! 🌟

**Comment by criticic** [comment]
claim
