### ISSUE TITLE
repair the bottom nav bar 

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/Text-It#143]
### 🚀 GitHub Issue: Repair Bottom Nav Bar Design

Hello contributors! 👋

#### **Description:**

The current state of the bottom navigation bar in `baseHomeActivity` needs improvement to align with our design standards. Your mission, should you choose to accept it, is to bring it in line with the specified design.

#### **Steps to Reproduce:**

1. Open the `activity_base_home.xml` file.
2. Locate the `BottomNavigationView` with ID `bottomNavView`.
3. Adjust the layout and styling to match the design specifications.
4. Ensure that the icons and text are visually appealing.

#### **Deadline:**

Your deadline for this task is 2 days. Please submit your changes by [insert deadline date].

**Comment by criticic** [comment]
claim

**Comment by keshavkhetan123** [comment]
claim

**Comment by Apoorv012** [comment]
claim

**Comment by MonuGit9** [comment]
claim
