### ISSUE TITLE
“I'm the king of the world!” -Titanic, 1997

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/Text-It#151]
### Description
Your task is to enhance the app by adding a screen that prompts the user to set a profile picture after signing up. The design of this screen should align with the current aesthetics of the app.

#### Detailed Steps:

1. **Profile Picture Screen:**
   - Create a new screen after the signup page.
   - Design the screen to ask the user to upload a profile picture.
   - Ensure that the design is consistent with the app's current look and feel.

2. **Image Handling:**
   - If the user signs up using email, prompt them to upload a profile picture.
   - If the user signs up through Google, Facebook, or any other method that doesn't involve email:
     - Check if the user has a profile picture associated with their account.
     - If available, use the obtained picture.
     - If not available, use the default Google account profile picture or Facebook profile picture.

3. **Integration with Profile Fragment:**
   - After the user selects or the default picture is obtained, assign it to the `ImageView` in the Profile Fragment.
   - Ensure smooth transitions and user-friendly interactions.

**Comment by criticic** [comment]
claim

**Comment by DikshantK2004** [comment]
Claim

**Comment by MonuGit9** [comment]
Claim

**Comment by DikshantK2004** [comment]
Please unassign me from this task

**Comment by criticic** [comment]
claim
