### ISSUE TITLE
“May the Force be with you.” -Star Wars, 1977

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/Text-It#152]
### Description

Your current task is to repair and enhance the Settings Fragment in the app. The existing design is not rendering correctly, causing the text to be jumbled when the screen is opened. Your goal is to bring the Settings Fragment in line with the provided design. also add a button to signout too .. ⭐ 

#### Detailed Steps:

1. **Settings Fragment Repair:**
   - Identify and fix the issues causing the text to be mixed up when the Settings Fragment is opened.
   - Ensure that the layout is rendering properly, and all text elements are displayed as intended.

2. **Design Consistency:**
   - Align the Settings Fragment design with the provided design specifications.
   - Pay attention to details such as font styles, colors, and spacing to achieve a consistent look.

---
![set](https://github.com/opencodeiiita/Text-It/assets/87519281/a57d6c28-e3a2-4128-91bf-037d052facae)

**Comment by MonuGit9** [comment]
Claim

**Comment by insanecoder02** [comment]
@MonuGit9 your deadline is near
