### ISSUE TITLE
“It's alive! It's alive!” -Frankenstein, 1931

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/Text-It#153]
### Description

Your current task is to repair and enhance the Contact Fragment in the app. The existing design is not rendering correctly, causing the text to be jumbled when the screen is opened. Your goal is to bring the Contact Fragment in line with the provided design.

#### Detailed Steps:

1. **Contact Fragment Repair:**
   - Identify and fix the issues causing the text to be mixed up when the Contact  Fragment is opened.
   - Ensure that the layout is rendering properly, and all text elements are displayed as intended.

2. **Design Consistency:**
   - Align the Contact Fragment design with the provided design specifications.
   - Pay attention to details such as font styles, colors, and spacing to achieve a consistent look.

---
![conot](https://github.com/opencodeiiita/Text-It/assets/87519281/8c80af2f-6958-4080-a1d3-0fd0917f6332)

**Comment by keshavkhetan123** [comment]
claim

**Comment by MonuGit9** [comment]
Claim

**Comment by insanecoder02** [comment]
@keshavkhetan123 your deadline is near

**Comment by MonuGit9** [comment]
Claim

**Comment by Apoorv012** [comment]
claim

**Comment by Parth4git** [comment]
claim

**Comment by MonuGit9** [comment]
Claim

**Comment by sarthakvermaa** [comment]
claim

**Comment by Aastha-ojha-20** [comment]
Claim

**Comment by Apoorv012** [comment]
@insanecoder02 I only have 2 pending issues

**Comment by insanecoder02** [comment]
> @insanecoder02 I only have 2 pending issues

Dear @Apoorv012 that time i didn't saw your both the PR's and i wasn't aware that you already submitted those.

**Comment by Apoorv012** [comment]
Is anything possible for now?

**Comment by insanecoder02** [comment]
Sorry but the task has already been assigned for now.

**Comment by Apoorv012** [comment]
ok, no problem :)
