### ISSUE TITLE
I'll be back.” -The Terminator, 1984

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/Text-It#154]
### Description

Your new task is to improve the authentication process in the app. The goal is to enhance the user experience and address missing details as outlined in the Figma file.

#### Detailed Steps:

1. **Make Screens Scrollable:**
   - Ensure that all screens before the HomeActivity are scrollable.
   - This includes screens involved in the authentication process.

2. **Password Visibility Toggle:**
   - Add buttons to toggle password visibility.
   - When pressed, change the password text to asterisks (***), and revert to normal text when pressed again.

3. **Error Animation for Confirm Password:**
   - Implement a visually appealing error animation when the entered password and confirm password do not match.
   - Consider highlighting the password box in red or using a suitable animation to indicate the error.

4. **Figma File Reference:**
   - Refer to the Figma file for additional details on the missing elements.
   - Make sure to incorporate any design specifications or features outlined in the Figma file.
---
https://www.figma.com/file/9xTKRAgvwCvi3ybLfZlqNH/OpenCode?type=design&node-id=17%3A2&mode=design&t=qSEedwOnwcwc0ZGo-1

**Comment by MonuGit9** [comment]
Claim

**Comment by kushal7201** [comment]
Claim

**Comment by abhisheksharma010** [comment]
Claim

**Comment by insanecoder02** [comment]
@kushal7201 your deadilne is near
