### ISSUE TITLE
“My precious.” -The Lord of the Rings: Two Towers, 2002

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/Text-It#155]
### Description
Your task is to add otp verification of the mobile number , 

#### Detailed Steps:

1. **Signup Section Updates:**
   - Modify the signup section to include fields for the user's phone number, along with existing fields for email, name, and password.
   - Ensure proper validation for the phone number field to match the required format.

2. **Save User Data in Firestore:**
   - Upon signup, save the user's credentials (uid, email, name, password, phone number) in the Firestore database.
   - Create a collection of users with documents containing the mentioned properties.

3. **Phone Number Verification using Firebase OTP:**
   - Implement phone number verification during signup using Firebase OTP.
   - Utilize Firebase authentication services to send an OTP to the user's phone number for verification.
   - Refer to this
   -  [video tutorial](https://www.youtube.com/watch?v=ZLOUggIEqzo) for guidance on Firebase phone number authentication.
   - the redirect the user to homeActivity after succesfull signup 

4.  in the signup process through email for now remove the email verfication part that would be done seprately in the profile section . 

Disclamier apply this only to the email signup process where google or facebook is not involved .
ty and user experience of your authentication system.

**Comment by criticic** [comment]
claim

**Comment by DikshantK2004** [comment]
Claim

**Comment by MonuGit9** [comment]
Claim
