### ISSUE TITLE
“Just keep swimming.” -Finding Nemo, 2003

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/Text-It#157]
## Bug: Skipping Splash Screen Bypasses Permission Requests

🐛 **Bug Summary:**
1. When users somehow manage to skip the splash screen, the subsequent steps for requesting permissions (e.g., notifications, camera) are also skipped. This results in missing essential permissions and impacts the functionality of the application. So your task is to fix this bug 

2.  Second  to modify the app's code such that after  authentication throuhg google ther users's email id  and name , profile pic here it would be default  google profile pic and name  would be saved  to firestore collection called "USERS" . 
each of the USERS's  document should have atlest 3 properties for now email id , name,  profile  pic 

hint- : to save profile pic  in the firebase you first would have to uplod it in the storage and then genrate an url for it and then push the imageurl in place of profile  pic 

📆 **Deadline:**
2 days ⏲️

**Comment by criticic** [comment]
claim

**Comment by MonuGit9** [comment]
Claim

**Comment by kushal7201** [comment]
Claim
