### ISSUE TITLE
“Part Of The Journey Is The End.”  ~Tony Stark

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/Text-It#163]
**Design Enhancement for Settings Fragment**

🛠 **Task Description:**
The task is to enhance the design of the Settings fragment to match the specifications provided in the Figma file. Additionally, create separate fragments for each button present in the Settings page. Keep the initial state of the pages blank and insert a text box indicating the page name for easy identification.

📆 **Deadline:**
Two days from the creation of this issue.

**🚧 Implementation Details:**
1. **Settings Fragment:**
   - Adjust the layout and styling to match the design from the Figma file.
   - Ensure accurate placement of elements, including buttons, text fields, and any other components.
   - Pay attention to color schemes, font styles, and overall aesthetics.

2. **Individual Button Fragments:**
   - Create separate fragments for each button present in the Settings page.
   - Each fragment should initially be blank with only a text box stating the button's purpose or name.

3. **Identifying Text Boxes:**
   - Use a bold font for the text boxes indicating the page names to enhance visibility.
   - Utilize appropriate emoji icons to make the identification process more engaging and straightforward.
ion.

🚀 **Happy contribution!** 🌟

**Comment by criticic** [comment]
claim
