### ISSUE TITLE
"While You Slept, The World Changed." ~Charles Xavier

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/Text-It#164]
** UI Implementation and Bug Fix for Call and Contact Fragments**

🛠 **Task Description:**

1. **Call Fragment UI:**
   - Implement the UI for the Call fragment.
   - Include a RecyclerView to display a list of names.
   - Each name in the list should have options for phone and message (no functionality needed at this stage).
   - Fetch and display users from the "users" collection in the database.
   - Add additional dummy names to the "users" collection for testing purposes.

2. **Contact Fragment Bug Fix:**
   - Investigate and resolve the crash issue in the Contact fragment.
   - Ensure that the Contact fragment uses the "users" collection to maintain the list of users.
   - Verify the implementation to prevent future crashes.

**📆 Deadline:**
Please complete the assigned tasks within a reasonable timeframe to facilitate testing and integration.
---
![call](https://github.com/opencodeiiita/Text-It/assets/87519281/5edeb755-3a7e-4074-8011-b170f8148477)

**Comment by criticic** [comment]
claim ()

**Comment by DikshantK2004** [comment]
Claim
