### ISSUE TITLE
"I Am Fire And Life Incarnate! Now And Forever - I Am Phoenix!"

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/Text-It#165]
**Design Implementation for ChatFragment and Individual Chat Layouts**

🛠 **Task Description:**

1. **ChatFragment Design:**
   - Create the UI design for the ChatFragment where real-time chatting will take place.
   - Include the necessary components like message input area, send button, and a RecyclerView to display the conversation.
   - Design a clean and user-friendly interface that aligns with the overall app aesthetic.

2. **Individual Chat Layouts:**
   - Design layouts for individual chat messages to be used for both sending and receiving messages.
   - Consider differentiating between user-sent messages and received messages, possibly using distinct colors or icons.
   - Ensure that the layout provides a clear distinction between messages and includes essential details like timestamps.

**📆 Deadline:**
Please complete the assigned tasks within a reasonable timeframe to facilitate testing and integration.

---
![Message](https://github.com/opencodeiiita/Text-It/assets/87519281/650d2a03-189d-4b9a-b2ef-26f5d2fef2ba)

**Comment by DikshantK2004** [comment]
Claim
