### ISSUE TITLE
Bug fixes...

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/Text-It#177]
Certainly! Here is a revised version using Markdown with added emojis and text formatting:

---

🐛 **Bug Fixes for the App**

1. 📱 **Message Fragment Placement Issue:**
   The message fragment is supposed to be present at its designated place in the bottom navigation bar. However, currently, the chat fragment is being displayed in that position. 🔄 Please fix this issue to ensure the correct placement of the message fragment.

2. 🎨 **Contact Page Design Mismatch:**
   The design of the contact page does not align with the Figma design. 🛠 Kindly adjust the layout and styles to match the specified Figma design accurately. You can see the desgin from the figma file if you dont have link then pls ask for it .

3. ⚙️ **Settings Fragment Design Refactoring:**
   The current design of the settings fragment is suboptimal, with multiple constraint layouts being used. 🛠 Your task is to improve the design according to the specified design guidelines. Try to use a single constraint layout that contains multiple view groups organized within a LinearLayout for better structure and maintainability.

---

also to work on this issue you have to be added in the firebase console so if you are not then pls message for that

**Comment by DikshantK2004** [comment]
Claim

**Comment by parth1egend** [comment]
claim

**Comment by DikshantK2004** [comment]
@muffinboy19 Is the issue generated by GPT 🤣🤣🤣

**Comment by muffinboy19** [comment]
umm...yess

**Comment by kushal7201** [comment]
Claim

**Comment by muffinboy19** [comment]
sorry we are clsing this issue as this has gone very old . @DikshantK2004

**Comment by DikshantK2004** [comment]
> sorry we are clsing this issue as this has gone very old . @DikshantK2004 

Why did you ping me?
