### ISSUE TITLE
The Godfather (1972)

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/Text-It#180]
🔄 **Authentication Process Enhancements:**

1. 🌐 **Google Authentication Method:**
   - **User Information Collection:**
     When a user authenticates using the Google button method, prompt them to provide their username and phone number.
   - **Data Storage:**
     Save the collected username and phone number information to Firebase in a collection named "users."
   - **Profile Picture Fix:**
     Address the issue where the app does not prompt users to provide a profile picture during registration via the Google button method. Ensure that users can upload their profile picture seamlessly.

2. ✉️ **Email Authentication Method:**
   - **OTP Removal:**
     Streamline the email authentication process by removing the OTP requirement to enhance user experience.
   - **User Input:**
     Instead of OTP, collect the user's phone number directly during the email authentication method.
   - **Data Storage:**
     Save the collected phone number information to Firebase in the "users" collection under relevant field properties.

   **Note:** Ensure that these changes are implemented smoothly and do not compromise the security or reliability of the authentication process.

---

**Comment by DikshantK2004** [comment]
Claim

**Comment by parth1egend** [comment]
claim

**Comment by DikshantK2004** [comment]
Claim

**Comment by Aditya2174** [comment]
claim
