### ISSUE TITLE
"“There's no crying in baseball!” -A League of Their Own, 1992" 

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/Text-It#185]
:rotating_light: Attention! :rotating_light:

The username window is appearing prematurely after 2-3 seconds on the landing page, without any button press.

:wrench: Tasks:

Google Sign-In Pathway:

Trigger username screen only after Google button click.
Implement Google sign-in and automatically use default profile picture.
Redirect to home screen upon successful sign-in.
Add loading view and toasts for user-friendliness. :bread: :coffee:

Email Pathway:
same error here the username screen pop ups without any action .
Sequence screens as follows:
Username screen (includes phone number) only whne the go with email is selected.
Profile picture selection
Email authentication
Home screen
Incorporate loading views and toasts. :hourglass: 🍞 

Firestore Collection:

Maintain a collection with:
Username
User profile picture URL
User email ID
User UID
Check for existing collection before creation.

:heart: Let's make this navigation experience smooth and delightful! :rocket:

**Comment by Apoorv012** [comment]
claim

**Comment by MonuGit9** [comment]
Claim

**Comment by MonuGit9** [comment]
Claim

**Comment by kushal7201** [comment]
Claim
