### ISSUE TITLE
"“There's no crying in baseball!” -A League of Their Own, 1992"

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/Text-It#186]
#### 1. Resolve Visibility Issue in MessageFragment
- **Issue Description:** 📧 Address the visibility problem within the MessageFragment where the message recycle view is not currently visible, and is not showing ther users to chat , also  the chat fragment is displayed when the mesage button is clicked.

- **Task Details:**
   - Investigate and fix the issue causing the message recycle view to be hidden in the MessageFragment.
   - Ensure that the chat fragment is not displayed within the MessageFragment's space.

#### 2. Implement Chat Feature
- **Issue Description:** 🗨 Implement a functional chat feature by following the guidelines provided in the video tutorial.
- **Task Details:**
   - Watch the tutorial video at [YouTube - Chat Feature Implementation](https://www.youtube.com/watch?v=8Pv96bvBJL4) for step-by-step instructions.
   - Utilize the existing resource link for the chat layout, ensuring compatibility with the current project.
   - Integrate the chat feature into the application, making sure it aligns with the design and functionality demonstrated in the video.
   - Test the messaging feature thoroughly to verify its proper functioning.
   - The pull request for this task will only be merged once the messaging feature is successfully implemented.
   
   
   the points for this issue is  80 .
   since alredy someone has implemented some part of the chat feature (which is presnt in the chatfragment itself and which works very well so try to utelise this too)

**Comment by criticic** [comment]
claim

**Comment by MonuGit9** [comment]
Claim

**Comment by DikshantK2004** [comment]
Claim

**Comment by MonuGit9** [comment]
Claim
