### ISSUE TITLE
"“E.T. phone home.” -E.T. the Extra-Terrestrial, 1982" 

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/Text-It#187]
#### Implement Call Feature in Call Fragment
- **Issue Description:** ☎️ Integrate a call feature within the Call Fragment that allows users to initiate calls to specific individuals.
- **Task Details:**
   - Utilize the inbuilt phone dialer for seamless call initiation.
   - Implement logic to forward the designated phone number to the dialer when the call emoji is pressed.
   - Incorporate error handling to display a toast when the call cannot be connected.
   - Utilize loading views to enhance user experience during call initiation.
   - Ensure proper communication with the user through toasts when the call is successful.
   - When the "Call+" button is clicked, open a list of names to call from the user collection in the Firebase Firestore.
   - Enable the calling feature within this list as well.
   - Display the correct profile icon in both the call RecyclerView and the user list for a more personalized experience.

**Comment by DikshantK2004** [comment]
Claim

**Comment by MonuGit9** [comment]
Claim

**Comment by Apoorv012** [comment]
claim
