### ISSUE TITLE
"“You can't handle the truth!” -A Few Good Men, 1992" 

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/Text-It#188]
#### Match Contact Screen with Figma Design
- **Issue Description:** 🎨 Rectify the inconsistency between the current Contact screen and the Figma design.
- **Task Details:**
   - Carefully review the Figma design for the Contact screen.
   - Adjust the layout, colors, and elements to align with the specified design in Figma.
   - Ensure a consistent and cohesive visual representation on the Contact screen.

#### Implement Contact Detail Fragment
- **Issue Description:** 📞 Develop a new fragment that appears when a contact is clicked on the Contact screen, displaying detailed information and providing options to chat and call.
- **Task Details:**
   - Create a new fragment for displaying contact details.
   - Include fields for comprehensive contact information such as name, phone number, etc.
   - Integrate buttons to initiate chat and call functionalities directly from the contact details page.
   - Ensure a smooth transition between the Contact screen and the newly created contact details fragment.
   - Enhance the user experience with proper navigation and a visually pleasing design.
   - also add the search feature in the call framgent toooo.

---
the desgin of this screen might already be present so you can search the project for it 
![aa](https://github.com/opencodeiiita/Text-It/assets/87519281/0683a45c-38d6-4943-aea8-c7215bd0893d)

**Comment by sarthakvermaa** [comment]
calim

**Comment by criticic** [comment]
claim

**Comment by MonuGit9** [comment]
Claim

**Comment by Apoorv012** [comment]
claim

**Comment by insanecoder02** [comment]
@sarthakvermaa plz send your PR asap.

**Comment by criticic** [comment]
claim

**Comment by sarthakvermaa** [comment]
claim

**Comment by muffinboy19** [comment]
opne to claim

**Comment by sarthakvermaa** [comment]
claim

**Comment by criticic** [comment]
claim

**Comment by sarthakvermaa** [comment]
@muffinboy19 sending pr in a while
