### ISSUE TITLE
"“A martini. Shaken, not stirred.” -Goldfinger, 1964" 

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/Text-It#189]
#### Refactor Settings Fragment to Match Figma Design
- **Issue Description:** 🛠️ Enhance the appearance and functionality of the Settings fragment to align with the specified Figma design.
- **Task Details:**
   - The current design is not matching the figma design change it .

#### Implement Navigation Structure for Settings Options
- **Issue Description:** 🚀 Enhance the user experience within the Settings fragment by implementing a navigation structure.
- **Task Details:**
   - Introduce a new screen structure for each option in the Settings fragment (e.g., Help, Notifications, Chats).
   - Include a back button on each screen to navigate back to the main Settings page.
   - Display the name of the screen using a TextView for clarity.
   - Implement the navigation logic for smooth transitions between the main Settings page and individual option screens.

#### Update Profile Fragment Integration
- **Issue Description:** 🖼️ Integrate the correct user profile picture into the Settings page and ensure the profile fragment opens upon clicking the profile icon.
- **Task Details:**
   - Retrieve the user's profile picture from the user data.
   - Replace the dummy profile picture with the actual user's profile picture on the Settings page.
   - Implement the functionality to open the profile fragment when the profile icon is clicked.

**Comment by criticic** [comment]
claim

**Comment by sarthakvermaa** [comment]
claim

**Comment by MonuGit9** [comment]
Claim
