### ISSUE TITLE
"“Life is a banquet, and most poor suckers are starving to death!” -Auntie Mame, 1958" 

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/Text-It#190]
#### Update Facebook Authentication Flow
- **Issue Description:** 🔒 Refine the Facebook authentication process to align with specified navigation and criteria.
- **Task Details:**
   - Ensure the Facebook authentication process requests and stores the following details:
     - User's username
     - Profile picture (use default Facebook profile picture if not provided by the user)
     - Phone number
   - Save these details in the same Firestore collection used for storing other user information.

#### Implement Status Feature in Profile Fragment
- **Issue Description:** 🚀 Introduce a status feature accessible from the Profile fragment, allowing users to share and view status updates.
- **Task Details:**
   - Add a "Status" button to the Profile fragment.
   - Upon pressing the button, prompt the user to choose an image from the gallery or capture one using the camera.
   - Display the selected image to the user.
   - Include a button to confirm and update the status.
   - Provide a confirmation toast after successfully updating the status.

#### Display Status Image in Message Fragment
- **Issue Description:** 📸 Enhance the Message fragment to display user statuses when clicked.
- **Task Details:**
   - Implement a mechanism to view user statuses in the Message fragment.
   - When a user's status is clicked, display the associated image for 5 seconds.
   - Ensure a smooth and user-friendly experience during status viewing.

this isseu if of 80 points

**Comment by Apoorv012** [comment]
claim

**Comment by insanecoder02** [comment]
@Apoorv012 plz send your PR asap.

**Comment by criticic** [comment]
claim

**Comment by muffinboy19** [comment]
opne to claim

**Comment by criticic** [comment]
claim
