### ISSUE TITLE
Design the Logo

### ISSUE THREAD

**Issue by insanecoder02** [opencodeiiita/Text-It#2]
**Design a Good Logo for the App 🎨**

- Attach📎 a screenshot/folder link of your work with your PR.
- Point🥇 will only be awarded to the PR that is accepted.

**PS: This issue is open for all, so no need to claim this issue. You can directly create a pull request**
**Note: This issue will be active for only _3 days._ ⏳**

_Happy Contributing!😊_

**Comment by shrutikarathi6** [comment]
![Uploading Screenshot 2023-12-14 164809.png…]()
