### ISSUE TITLE
Register User Activity

### ISSUE THREAD

**Issue by insanecoder02** [opencodeiiita/Text-It#83]
Create a **Register Activity** asking the user its :- 
- name
- email
- password
- confirm password

Ensure a visually appealing design to enhance user experience. 🎨

_Happy contributing! 😊_

**Comment by Apoorv012** [comment]
claim

**Comment by CodinJack** [comment]
claim

**Comment by Murdock9803** [comment]
Claim

**Comment by kushal7201** [comment]
claim

**Comment by vasusingla545** [comment]
ckaim

**Comment by AngadManroy** [comment]
claim

**Comment by Reene-Simon** [comment]
claim

**Comment by insanecoder02** [comment]
assigned to @Apoorv012

**Comment by Nandinig24** [comment]
Claim

**Comment by divyanshrai03** [comment]
claim

**Comment by sanjayh-2022** [comment]
Claim

**Comment by Apoorv012** [comment]
Sorry, could you please unassign me.

**Comment by muffinboy19** [comment]
comment from here will be considered

**Comment by chiragmalik2612** [comment]
claim

**Comment by CodinJack** [comment]
claim

**Comment by muffinboy19** [comment]
@chiragmalik2612  is reassigned the issue

**Comment by chiragmalik2612** [comment]
@muffinboy19 where to make pull request / show design.

**Comment by insanecoder02** [comment]
You have to create a new activity for register user and attach the png of your work in PR

**Comment by muffinboy19** [comment]
The issue is reassgined to @CodinJack
