### ISSUE TITLE
Register/Logged in

### ISSUE THREAD

**Issue by insanecoder02** [opencodeiiita/Text-It#84]
Write the logic code for **Register User** and **logging the user** in two different separate .kt files

_Happy Contributing!!😊_

**Comment by anshuman-rai-27** [comment]
Claim

**Comment by vasusingla545** [comment]
claim

**Comment by sarthakvermaa** [comment]
claim

**Comment by kushal7201** [comment]
claim

**Comment by AngadManroy** [comment]
Claim

**Comment by insanecoder02** [comment]
assigned to @anshuman-rai-27

**Comment by muffinboy19** [comment]
issue is solved by @anshuman-rai-27
