### ISSUE TITLE
Add a bottom nav bar 

### ISSUE THREAD

**Issue by muffinboy19** [opencodeiiita/Text-It#92]
#### Tasks
1. Implement a bottom navigation bar in the Home activity.
2. Include three icons in the navigation bar.

#### Notes
- Ensure smooth navigation and a visually appealing design.
- Customize the icons and appearance based on the provided design inspiration.

#### Deadline
⏰ **2 days from claim date**

---

**Happy Contributing!** 🎉

**Comment by QuantTitan** [comment]
claim

**Comment by muffinboy19** [comment]
all the best @QuantTitan

**Comment by insanecoder02** [comment]
@QuantTitan You have to submit the PR before 2:00 pm for this task
else this will be assigned to another contibutor

**Comment by kushal7201** [comment]
Claim

**Comment by kushal7201** [comment]
Claim @QuantTitan

**Comment by kushal7201** [comment]
Claim @QuantTitan

**Comment by kushal7201** [comment]
Claim @QuantTitan

**Comment by muffinboy19** [comment]
It is open issue now you can now do the task and just send a pr

**Comment by kushal7201** [comment]
ok

**Comment by keshavkhetan123** [comment]
claim

**Comment by muffinboy19** [comment]
assigned to @keshavkhetan123

**Comment by insanecoder02** [comment]
@keshavkhetan123 deadline for this issue is 6"00 pm. Please submit your PR before that

**Comment by muffinboy19** [comment]
@keshavkhetan123  pls make a PR your deadline is over now

**Comment by muffinboy19** [comment]
closed
