### ISSUE TITLE
Ohhh damn!!! I forgot it again

### ISSUE THREAD

**Issue by insanecoder02** [opencodeiiita/Text-It#99]
In this task, you have to add an option for forgot password in LoginUser() activity **[already created]**

also you have to write the code for navigation through the existing activities:
- splash -> Login
- Login -> Register and vice versa
- Register -> MainActivity
- Login -> MainAcvitvity

Also forgot password should open in a new activity....
Coming Soon!!!!

till then

_Happy contributing😊!!!_

**Comment by harshsingh554** [comment]
claim

**Comment by insanecoder02** [comment]
assigned to @harshsingh554

**Comment by muffinboy19** [comment]
reminder @harshsingh554  the task deadline is near

**Comment by tonyStark-Jr** [comment]
claim

**Comment by muffinboy19** [comment]
@tonyStark-Jr  we are closing this issue  due to some erros in the project , we would assing you a different issue of same point
